name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check coverage
      run: cargo install cargo-tarpaulin && cargo tarpaulin --ignore-tests
    - name: Check linting
      run: cargo clippy -- -D warnings
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Audit security vulnerabilities
      run: cargo install cargo-audit && cargo audit
